sudo: required
services:
- docker
before_install:
- docker build -t sg/slack-agent -f ./Dockerfile.dev .
script:
- docker run sg/slack-agent npm run test -- --coverage
notifications:
  slack:
    secure: vU2gbICTg9SSi2V1hrq/j6V3oHWkG5ZdD0DC/ND+vBAGi71RMTEyFcRtLjQlA+kz8zLIfZYKPcXkzBoQnn0cwavca3YaZW+p06euD9LJPPArGx/qoh84VF2NEd0kvkEYDONo7ujR+Jk/j8spJJGz4iruwUPkkoCR1mPcU0oYkMDia40KoqnrHnWjDbA9VIWWODlcmn9bJWmueP+xGfD6v/lE1RuEyqBk64EJjSYbLP62XfzafcjScpWHI2IwtFF7YBvp1YO/3gCJl3vzpPryQ6WKUPdsOaOir5YDwWUY73AU+Gs87axiw/RriPRHW5yvDbKmpVzpW83ByvRHN190zRrSfBqdqFGA37DevSVMQXLh/qz2ZG70sByFcQQJ78YwXWyYLK2UEURxSCir776Nti36CvHSu5yeiynxp8h5T7fbUZKZg7fBYe4f8dpoK/GktCfQcnDcKUeuWTXQ+sWCT0eL7+Sj/WWhZMXIIKybDNJ9rCvn58R1JwYTXacgqJ7/KdZiH5tMLnHdF50vwEkcfGAJOXzTSmXXFDREdH3/UVRSxdmGMH/iSSrnkCKSPHH0hd9uZBDwLkoWYYn4LtAZo/P8sjSZlWBAnVmdBNxVYOCF+4GSEC5PJlI9z2Rn05DOiqfaKWahzMNrKFU0y/sqO2zcjYQTQBCxMyBxvEIubIg=
