sudo: required
services:
- docker
before_install:
- docker build -t sg/slack-agent -f ./Dockerfile.dev .
script:
- docker run sg/slack-agent npm run test -- --coverage
notifications:
  slack:
    secure: LkxNZw33noK7+GrPCaTWDbi5MGkkeLeJ2bJz1LvZJOif5ll5jhErzuOTsA9+vbSRrQJofNGB7iJmSdfBw6o+l85fJEhT3QnItsD9LsVIhm4BtTbxfFQayWgvr3dpV0V06jxkP4ovEUOeR2wc9zNdIv5XM5J7yoR30DAydnPP5u1JCTsprpWOoTnABJmJ2ybuwviEMAdp6A8Y7v1gRQRjyKOnpryoGwSBTbreG+x9fyw5JbRasb6KGycGuBs3ZZJ9jfgKEHsH+nFWNE1lR0pVYklxBBflZJbfyz0gFs6I1S2pkMgltjebMl7+6ePRCDGAd4ApsKOSnEZGYsFXMusLxlWarlvQwdyJZVEiXz1A2Ti1LQ5f65RSpEEhC6vZ8nk3sm3R4A4CtKBMOF+V9BHVzVqRtaGZWDcnOVX5dbWgiA0DdqbCTFhlulYp40V2P5/59HlDzSmxf9aye/1RjBLoxbQRJ/SbdlUw3NUJ1XLKaFoHdHwYaOI2bzfHEos/PB7sXYRNZlBN9D7L2JZSzNiVrQk5zawjy/xqAFYIMbjgwXMPqRr+6HsiOhw7zwHnr63wsi6lfP+ycQAlNuzX6vulAjcbImNftXn9ve1bavHsIojBhelpMQmwtnxpqfIMQoLrYjIdKv5r73JEOiGDctAtmeqsk4bjx5e8b3OBf+Ws0JU=
