version: '3'
networks:
  test_lambda:
###############
### for test usage only
###############
services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb
    ports:
      - 8000:8000
    networks:
      - test_lambda

  lambda:
    image: 'lambci/lambda:nodejs8.10'
    hostname: slack-agent
    volumes:
      - ./:/var/task
    environment:
      - ENV_STAGE=dev
      - CLIENT_ID=123
      - CLIENT_SCOPES=scopes
      - SIGNING_SECRET=123
      - TABLE_NAME=parking-dev
      - EVENT={"body":{"City":"Waw", "Place":"1"}}
    ports:
      - 80:80
      - 8080:8080
    command: handler.parkingPlace $EVENT
    networks:
      - test_lambda
    links: 
      - dynamodb
  