service: slack-agent
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    SLACK_CLIENT_ID: ${ssm:SLACK_AGENT_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${ssm:SLACK_AGENT_CLIENT_ID}
    SLACK_SIGNING_SECRET:  ${ssm:SLACK_AGENT_SIGING_SECRET}
    SLACK_CLIENT_SCOPES: ${ssm:SLACK_AGENT_CLIENT_SCOPE} 
    TABLE_NAME: ${ssm:SLACK_AGENT_TABLE_NAME}
  iamRoleStatements:    
    - Effect: Allow
      Resource: "*"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
region: us-east-1
functions:
  authorization:
    handler: handler.authorization
    events:
      - http:
          path: slack/authorization
          method: get
  parkingPlace:
    handler: handler.parkingPlace
    events:
      - http:
          path: slack/parkingPlace
          method: post
  parkingPlaceList:
    handler: handler.parkingPlaceList
    events:
      - http:
          path: slack/parkingPlaceList
          method: post
resources:
  Resources:
    dynamodb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: parking
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1