service: slack-agent
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    SLACK_CLIENT_ID: '525399495920.526137174018'
    SLACK_CLIENT_SECRET: '7191fea58634df547eb10a5d63734f65'
  iamRoleStatements:    
    - Effect: Allow
      Resource: "*"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
region: us-east-2
functions:
  authorization:
    handler: handler.authorization
    events:
      - http:
          path: slack/authorization
          method: get
  placeReservation:
    handler: handler.placeReservation
    events:
      - http:
          path: slack/placeReservation
          method: post
resources:
  Resources:
    dynamodb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: reservation
        AttributeDefinitions:
          - AttributeName: reservation_id
            AttributeType: S
        KeySchema:
          - AttributeName: reservation_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1