version: '3'
networks:
  test_lambda:
###############
### for test usage only
###############
services:
# to test endpoint please modify "command"
# general syntax:
# "handler.<func_name> {\"body\":{<event_data>}}'"
# example:
# command: "handler.parkingPlaceList '{\"body\":{\"test\": \"123\"}}'"
  lambda:
    image: 'lambci/lambda:nodejs8.10'
    hostname: slack-agent
    volumes:
      - ../:/var/task
    environment:
      - ENV_STAGE=dev
      - CLIENT_ID=123
      - CLIENT_SCOPES=scopes
      - SIGNING_SECRET=123
      - PARKING_PLACES_TABLE=ParkingPlaces-dev
      - BOOKINGS_TABLE=Bookings-dev
      - LOCAL_DB=true
    command: "/handlers/${SLACK_AGENT_HANDLER}.${SLACK_AGENT_FUNCTION} '${SLACK_AGENT_EVENT_JSON}'"
    networks:
      - test_lambda
