  Resources:
    dynamodb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
          - AttributeName: Types
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
          - AttributeName: Types
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 10
            WriteCapacityUnits: 10