  Resources:
    dynamodb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.parkingPlaces}
        AttributeDefinitions:
        - AttributeName: City
          AttributeType: S
        - AttributeName: Place
          AttributeType: S
        KeySchema:
        - AttributeName: City
          KeyType: HASH
        - AttributeName: Place
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1