Resources:
  parkingPlaces:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.parkingPlaces}
      AttributeDefinitions:
        - AttributeName: City
          AttributeType: S
        - AttributeName: PlaceID
          AttributeType: S
      KeySchema:
        - AttributeName: City
          KeyType: HASH
        - AttributeName: PlaceID
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
